---
driver:
  name: vagrant
  network:
    - [ 'private_network', {ip: '192.168.33.11'}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[elk_forwarder::certs]
      - recipe[elk_forwarder::default]
    attributes:
      elk_forwarder:
        mocking: true
        config:
          network:
            servers:
              - _default-logstash.priv.evertrue.com:5043
          files:
            - paths:
                - /var/log/syslog
            - fields:
                type: syslog
