---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[elk_forwarder::certs]
      - recipe[elk_forwarder::default]
    attributes:
      elk_forwarder:
        certs:
          ca_data_bag: certificates
          ca_data_bag_item: logstash
          ca_data_bag_item_key: ca certificate
        config:
          network:
            servers:
              - _default-logstash.priv.evertrue.com:5043
          files:
            syslog:
              paths:
                - /var/log/syslog
              fields:
                type: syslog
